id: I5666A646
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T18:04:10+00:00'
last_modified: '2022-06-08T11:42:17.833736+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W18598
  title: བཻ་རོའི་རྣམ་ཐར་འདྲ་འབག་ཆེན་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9EB2:
      image_group_id: I1KG10018
      title: ''
      total_pages: 356
      order: 1
      base_file: 9EB2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
